### PR TITLE
Correct unescaped left brace in regex error.

### PR DESCRIPTION
**Pull request by jkeenan**
Detected when run against perl 5 blead v5.27.7-213-ga8e5118.

### CODE REVIEW

**Comment by jkeenan** [comment]
Getopt::Long::Descriptive has a test failure when tested against Perl 5 blead.  This prevents MooseX::Getopt, Catalyst::Runtime, etc., from being installed via 'cpanm'.

```
$ ./bin/perl -v | head -2 | tail -1
This is perl 5, version 27, subversion 8 (v5.27.8 (v5.27.7-213-ga8e5118)) built for x86_64-linux

$ ~/testing/blead/bin/prove -I~/testing/blead/lib -Ilib -v t/shortcircuit.t 
t/shortcircuit.t .. Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/(?:[:=][\d\w\+]+[%@]?({ <-- HERE \d*,\d*})?|[!+])$/ at /home/jkeenan/gitwork/zzzothers/Getopt-Long-Descriptive/lib/Getopt/Long/Descriptive.pm line 307.

ok 1 - no req: error
ok 2 - shortcircuit + default
ok 3 - req: no error
ok 4 - req: req1 specified
ok 5 - help: no error
ok 6 - help: help flag
ok 7 - help: only help
ok 8 - help + req: no error
ok 9 - help + req: help flag
ok 10 - help + req: only help
not ok 11 - no (unexpected) warnings (via done_testing)
#   Failed test 'no (unexpected) warnings (via done_testing)'
#   at t/shortcircuit.t line 84.
1..11
# Looks like you failed 1 test of 11.
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/11 subtests 

Test Summary Report
-------------------
t/shortcircuit.t (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  11
  Non-zero exit status: 1
Files=1, Tests=11,  0 wallclock secs ( 0.02 usr  0.00 sys +  0.06 cusr  0.00 csys =  0.08 CPU)
Result: FAIL
```
Because this distribution uses ```dist.ini```, I couldn't fully test my patch, but please evaluate pull request.  When applied, please let @karenetheridge know as well.

Thank you very much.
Jim Keenan

**Comment by karenetheridge** [comment]
+1 - rjbs, it would be great if this could be released soonish as it will unblock testing of reverse dependencies.

**Comment by jkeenan** [comment]
This was apparently by this very recent commit:
```
commit 0367231ce260cd08bcb13082d510e5778668bcc1
Author:     Karl Williamson <khw@cpan.org>
AuthorDate: Thu Jan 4 12:53:29 2018 -0700
Commit:     Karl Williamson <khw@cpan.org>
CommitDate: Fri Jan 19 12:52:15 2018 -0700
```

**Comment by eserte** [comment]
CPAN.pm users may use this distroprefs file for automatic patching: https://github.com/eserte/srezic-cpan-distroprefs/blob/master/Getopt-Long-Descriptive.yml

**Comment by karenetheridge** [comment]
Note: if the warnings test had been guarded by an AUTHOR_TESTING check (which it should be!) -- the test would warn but would not fail, so installation would not be blocked.

Please do:  `use if $ENV{AUTHOR_TESTING}, 'Test::Warnings';`  in tests.

**Comment by karenetheridge** [comment]
This was fixed in 0.101 - the PR can be closed.

**Pull request closed without merging**
